import React from 'react'

const generateQuizWithAnswersPDF  = async (quizData) => {
  try {
    const { default: jsPDF } = await import('jspdf');
    await import('jspdf-autotable');
    
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPosition = 20;
    
    // Header
    doc.setFillColor(16, 185, 129); // Green
    doc.rect(0, 0, pageWidth, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text(quizData.title || 'Quiz', pageWidth / 2, 12, { align: 'center' });
    doc.setFontSize(14);
    doc.text('Answer Key', pageWidth / 2, 20, { align: 'center' });
    
    // Metadata
    doc.setFontSize(10);
    doc.text(`Total Questions: ${quizData.questions.length}`, pageWidth / 2, 26, { align: 'center' });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth / 2, 31, { align: 'center' });
    
    yPosition = 45;
    doc.setTextColor(0, 0, 0);
    
    // Questions with answers
    quizData.questions.forEach((q, idx) => {
      // Check if we need a new page
      if (yPosition > pageHeight - 80) {
        doc.addPage();
        yPosition = 20;
      }
      
      // Question number
      doc.setFillColor(236, 253, 245); // Light green background
      doc.setDrawColor(16, 185, 129); // Green border
      doc.rect(10, yPosition, pageWidth - 20, 8, 'FD');
      doc.setTextColor(5, 150, 105);
      doc.setFontSize(10);
      doc.setFont(undefined, 'bold');
      doc.text(`Question ${idx + 1} of ${quizData.questions.length}`, 12, yPosition + 5);
      yPosition += 12;
      
      // Question text
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(11);
      doc.setFont(undefined, 'bold');
      const questionLines = doc.splitTextToSize(q.question, pageWidth - 30);
      doc.text(questionLines, 12, yPosition);
      yPosition += (questionLines.length * 6) + 5;
      
      // Options
      doc.setFont(undefined, 'normal');
      doc.setFontSize(10);
      q.options.forEach((opt, optIdx) => {
        const optionLabel = String.fromCharCode(65 + optIdx);
        const isCorrect = optIdx === q.correctAnswer;
        const optionLines = doc.splitTextToSize(`${optionLabel}. ${opt}`, pageWidth - 40);
        
        // Option box - highlight correct answer
        if (isCorrect) {
          doc.setFillColor(209, 250, 229); // Light green
          doc.setDrawColor(16, 185, 129); // Green border
          doc.setLineWidth(0.5);
        } else {
          doc.setFillColor(255, 255, 255);
          doc.setDrawColor(229, 231, 235);
          doc.setLineWidth(0.2);
        }
        
        const boxHeight = 7 + (optionLines.length - 1) * 5;
        doc.rect(15, yPosition - 4, pageWidth - 30, boxHeight, 'FD');
        
        // Text
        if (isCorrect) {
          doc.setTextColor(5, 150, 105);
          doc.setFont(undefined, 'bold');
        } else {
          doc.setTextColor(0, 0, 0);
          doc.setFont(undefined, 'normal');
        }
        doc.text(optionLines, 17, yPosition);
        
        // Checkmark for correct answer
        if (isCorrect) {
          doc.setTextColor(5, 150, 105);
          doc.text('✓', pageWidth - 20, yPosition);
        }
        
        yPosition += boxHeight + 2;
      });
      
      // Correct answer box
      doc.setFillColor(236, 253, 245);
      doc.setDrawColor(16, 185, 129);
      doc.setLineWidth(0.5);
      doc.rect(15, yPosition, pageWidth - 30, 10, 'FD');
      doc.setTextColor(5, 150, 105);
      doc.setFontSize(10);
      doc.setFont(undefined, 'bold');
      const correctLabel = String.fromCharCode(65 + q.correctAnswer);
      doc.text(`✓ Correct Answer: ${correctLabel}. ${q.options[q.correctAnswer]}`, 17, yPosition + 6);
      yPosition += 15;
      
      // Explanation
      if (q.explanation) {
        doc.setFillColor(239, 246, 255); // Light blue
        doc.setDrawColor(59, 130, 246);
        doc.setLineWidth(0.3);
        const explanationLines = doc.splitTextToSize(q.explanation, pageWidth - 35);
        const explanationHeight = 10 + (explanationLines.length * 5);
        doc.rect(15, yPosition, pageWidth - 30, explanationHeight, 'FD');
        doc.setTextColor(30, 64, 175);
        doc.setFont(undefined, 'bold');
        doc.setFontSize(9);
        doc.text('💡 Explanation:', 17, yPosition + 5);
        doc.setTextColor(0, 0, 0);
        doc.setFont(undefined, 'normal');
        doc.text(explanationLines, 17, yPosition + 10);
        yPosition += explanationHeight + 5;
      }
      
      yPosition += 10;
    });
    
    // Footer
    const totalPages = doc.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(156, 163, 175);
      doc.text(`Generated by AI Quiz Generator - Answer Key`, pageWidth / 2, pageHeight - 10, { align: 'center' });
      doc.text(`Page ${i} of ${totalPages}`, pageWidth - 15, pageHeight - 10, { align: 'right' });
    }
    
    // Save the PDF
    doc.save(`${quizData.title || 'Quiz'}_With_Answers.pdf`);
  } catch (error) {
    console.error('Error generating PDF:', error);
    alert('Please install jsPDF: npm install jspdf jspdf-autotable');
  }
}

export default generateQuizWithAnswersPDF 