import React from 'react'

const generateQuizOnlyPDF  = async(quizData) => {
 // Dynamic import for jsPDF (will work when you install the package)
  try {
    const { default: jsPDF } = await import('jspdf');
    await import('jspdf-autotable');
    
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const pageHeight = doc.internal.pageSize.getHeight();
    let yPosition = 20;
    
    // Header
    doc.setFillColor(59, 130, 246); // Blue
    doc.rect(0, 0, pageWidth, 35, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(20);
    doc.setFont(undefined, 'bold');
    doc.text(quizData.title || 'Quiz', pageWidth / 2, 15, { align: 'center' });
    
    // Metadata
    doc.setFontSize(10);
    doc.text(`Total Questions: ${quizData.questions.length}`, pageWidth / 2, 23, { align: 'center' });
    doc.text(`Date: ${new Date().toLocaleDateString()}`, pageWidth / 2, 28, { align: 'center' });
    if (quizData.language) {
      doc.text(`Language: ${quizData.language}`, pageWidth / 2, 33, { align: 'center' });
    }
    
    yPosition = 45;
    doc.setTextColor(0, 0, 0);
    
    // Instructions Box
    doc.setFillColor(254, 243, 199); // Yellow background
    doc.setDrawColor(245, 158, 11); // Orange border
    doc.rect(10, yPosition, pageWidth - 20, 25, 'FD');
    doc.setFontSize(11);
    doc.setFont(undefined, 'bold');
    doc.text('Instructions:', 15, yPosition + 7);
    doc.setFont(undefined, 'normal');
    doc.setFontSize(9);
    doc.text('• Read each question carefully', 15, yPosition + 13);
    doc.text('• Select the best answer for each question', 15, yPosition + 18);
    doc.text('• Write your answer in the space provided', 15, yPosition + 23);
    
    yPosition += 35;
    
    // Questions
    quizData.questions.forEach((q, idx) => {
      // Check if we need a new page
      if (yPosition > pageHeight - 70) {
        doc.addPage();
        yPosition = 20;
      }
      
      // Question number
      doc.setFillColor(239, 246, 255); // Light blue background
      doc.setDrawColor(59, 130, 246); // Blue border
      doc.rect(10, yPosition, pageWidth - 20, 8, 'FD');
      doc.setTextColor(59, 130, 246);
      doc.setFontSize(10);
      doc.setFont(undefined, 'bold');
      doc.text(`Question ${idx + 1} of ${quizData.questions.length}`, 12, yPosition + 5);
      yPosition += 12;
      
      // Question text
      doc.setTextColor(0, 0, 0);
      doc.setFontSize(11);
      doc.setFont(undefined, 'bold');
      const questionLines = doc.splitTextToSize(q.question, pageWidth - 30);
      doc.text(questionLines, 12, yPosition);
      yPosition += (questionLines.length * 6) + 5;
      
      // Options
      doc.setFont(undefined, 'normal');
      doc.setFontSize(10);
      q.options.forEach((opt, optIdx) => {
        const optionLabel = String.fromCharCode(65 + optIdx);
        const optionLines = doc.splitTextToSize(`${optionLabel}. ${opt}`, pageWidth - 35);
        
        // Option box
        doc.setDrawColor(229, 231, 235);
        doc.rect(15, yPosition - 4, pageWidth - 30, 7 + (optionLines.length - 1) * 5, 'D');
        doc.text(optionLines, 17, yPosition);
        yPosition += 7 + (optionLines.length - 1) * 5 + 2;
      });
      
      // Answer space
      doc.setDrawColor(209, 213, 219);
      doc.setLineDash([2, 2]);
      doc.rect(15, yPosition, pageWidth - 30, 10, 'D');
      doc.setLineDash([]);
      doc.setFontSize(9);
      doc.setFont(undefined, 'bold');
      doc.text('Your Answer: __________', 17, yPosition + 6);
      
      yPosition += 20;
    });
    
    // Footer
    const totalPages = doc.internal.pages.length - 1;
    for (let i = 1; i <= totalPages; i++) {
      doc.setPage(i);
      doc.setFontSize(8);
      doc.setTextColor(156, 163, 175);
      doc.text(`Generated by AI Quiz Generator`, pageWidth / 2, pageHeight - 10, { align: 'center' });
      doc.text(`Page ${i} of ${totalPages}`, pageWidth - 15, pageHeight - 10, { align: 'right' });
    }
    
    // Save the PDF
    doc.save(`${quizData.title || 'Quiz'}_Questions.pdf`);
  } catch (error) {
    console.error('Error generating PDF:', error);
    alert('Please install jsPDF: npm install jspdf jspdf-autotable');
  }
}

export default generateQuizOnlyPDF 